[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ft_package"
version = "0.0.1"
description = "A sample test package"
authors = [{name = "Nahyulee", email = "nahyulee@student.42seoul.kr"}]
dependencies = []
